### ISSUE TITLE
crash in test.py

### ISSUE THREAD

**Issue by wmax** [acoomans/instagram-filters#1]
The Problem:

instagram is crashing on particular filters, other filters work like a charm.
What am I doing wrong?

No idea what else to write for your information so please feel free to ask me about my problem :)

System:

Ubuntu 10.04 Server(64bit)
Python: 2.7.5
ImageMagick: 6.8.6 ( compiled with jpeg )

The error log( tried to run the built in tests/test.py ):

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    applyAll()
  File "test.py", line 23, in applyAll
    f.apply()
  File "/usr/local/lib/python2.7/site-packages/instagram_filters-0.1-py2.7.egg/instagram_filters/filters/kelvin.py", line 8, in apply
    self.frame("Kelvin.jpg");
  File "/usr/local/lib/python2.7/site-packages/instagram_filters-0.1-py2.7.egg/instagram_filters/decorations/frame.py", line 10, in frame
    frame = os.path.join(path, "frames", frame)
  File "/usr/local/lib/python2.7/site-packages/instagram_filters-0.1-py2.7.egg/instagram_filters/filter.py", line 26, in execute
    error = subprocess.check_output(command, shell=True, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'convert results/Kelvin.jpg ( '/usr/local/lib/python2.7/site-packages/instagram_filters-0.1-py2.7.egg/instagram_filters/decorations/frames/Kelvin.jpg' -resize 600x600! -unsharp 1.5x1.0+1.5+0.02 ) -flatten results/Kelvin.jpg' returned non-zero exit status 1

**Comment by acoomans** [comment]
I tried to reproduce your issue, but without any success (everything works on my -virtual- machine).
Can you give more details?
